### ISSUE TITLE
exception onResume

### ISSUE THREAD

**Issue by hamadasafi** [prabhat1707/EasyWayLocation#10]
@Override
    protected void onResume() {
        super.onResume();
        easyWayLocation.startLocation();  // here is exception
    }

**Comment by prabhat1707** [comment]
sorry for that @hamadasafi. can you please share the exception logs?

**Comment by hamadasafi** [comment]
This image https://drive.google.com/file/d/1_ob3kpFl-kTecyZkzPgdhealCKRc-12q/view?usp=sharing

```
2020-03-04 12:35:46.743 21228-21228/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-03-04 12:35:46.744 21228-21228/? E/Zygote: accessInfo : 1
2020-03-04 12:35:47.406 21228-21228/com.abdsafi.testcharts E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abdsafi.testcharts, PID: 21228
    java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at com.example.easywaylocation.EasyWayLocation.checkLocationSetting(EasyWayLocation.java:719)
        at com.example.easywaylocation.EasyWayLocation.startLocation(EasyWayLocation.java:343)
        at com.abdsafi.testcharts.MainActivity.onResume(MainActivity.java:90)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1416)
        at android.app.Activity.performResume(Activity.java:7612)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4015)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4055)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.example.easywaylocation.EasyWayLocation.checkLocationSetting(EasyWayLocation.java:719) 
        at com.example.easywaylocation.EasyWayLocation.startLocation(EasyWayLocation.java:343) 
        at com.abdsafi.testcharts.MainActivity.onResume(MainActivity.java:90) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1416) 
        at android.app.Activity.performResume(Activity.java:7612) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4015) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4055) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7099) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```

**Comment by hamadasafi** [comment]
@prabhat1707 ????

**Comment by prabhat1707** [comment]
Sorry, @hamadasafi for the delay as I checked on StackOverflow about this issue I found a solution.

`compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}`
[https://stackoverflow.com/questions/58482498/java-lang-bootstrapmethoderror-exception-from-call-site-2-bootstrap-method-on](url)
this is not related to my library issue. please use that solution if it does not work then lt me know.
